import Body from './body'

import { Inter } from 'next/font/google'
import { getGlobalData } from '@/lib/cosmic'

import main from "../styles/sass/main.module.scss"
import "../styles/general.css"



const inter = Inter({ subsets: ['latin'] })

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */


export async function generateMetadata() {
  const siteData = await getGlobalData();
  return {
    title: siteData.metadata.site_title,
    description: siteData.metadata.site_tag,
  };
}

export default async function RootLayout({ children }) {

  return (
    <>
      <html lang="en" className={main.fundo}>
        <Body className={inter.className}>
          {children}
          <div>{process.env.BUCKET_SLUG}</div>
        </Body>
      </html>
    </>
  )
}
